# Generated by Django 5.2.17 on 2026-08-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('POR_CONFIRMAR', 'Por Confirmar'), ('RECHAZADO', 'Rechazado'), ('PAGADO', 'Pagado'), ('PREPARANDO_PEDIDO', 'Preparando Pedido'), ('LISTO_PARA_ENTREGA', 'Listo para Entrega'), ('EN_TRANSITO', 'En Tránsito'), ('ENTREGADO', 'Entregado')], default='POR_CONFIRMAR', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(choices=[('OSMOSIS', 'Osmosis'), ('SUPERFILTRACION', 'Superfiltración'), ('INDUSTRIAL', 'Industrial')], max_length=15)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
