# Generated by Django 5.2.17 on 2026-08-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('PURIFICADORES', 'Purificadores'), ('FILTOS_REFACCIONES', 'Filtros y Refacciones'), ('PURIFICADORES_INDUSTRIALES', 'Purificadores Industriales')], max_length=30),
        ),
    ]
