# Generated by Django 5.2.17 on 2026-09-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('PURIFICADORES', 'Purificadores'), ('FILTROS_REFACCIONES', 'Filtros y Refacciones'), ('PURIFICADORES_INDUSTRIALES', 'Purificadores Industriales')], max_length=30),
        ),
    ]
